name: dynamo_calendar
description: "A Flutter project that Supports flexible and customizable calendar/date-time picker widget for Flutter applications, supporting multiple modes"

version: 1.0.0

repository: https://github.com/patushie/dynamo_calendar
homepage: https://github.com/patushie/dynamo_calendar
issue_tracker: https://github.com/patushie/dynamo_calendar/issues

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  intl: ^0.20.0
  table_calendar: ^3.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
